$$
線型写像/線形変換とは
二つの集合U,Vにおいて、Uの一つの要素を決めたとき、\\
それに対するVの要素がただ一つ決まるとき、この対応をUからVへの写像といい、\boldsymbol{f:U → V}と表現される。\\
さらに、\boldsymbol{U, V}がベクトル空間であり、\boldsymbol{f}が任意の\boldsymbol{x, y}について次を満たすとき、\boldsymbol{f}を線型写像という。\\
・f(\boldsymbol{x}+\boldsymbol{y})＝f(\boldsymbol{x})＋f(\boldsymbol{y})   　　（５−１）\\
・f(k\boldsymbol{x})＝kf(\boldsymbol{x}) (kは実数)　　　　　　       　　　　      （５−２）\\
特に、線型写像\boldsymbol{f:U → V}において、ベクトル空間\boldsymbol{U, V}が同じものであるとき、fを線形変換という。\\

\boldsymbol{R}^n ：すべての成分が実数で構成されるn次ベクトル全体の集合である、\\n次元実ベクトル空間を表す。\\
\boldsymbol{R}^n → \boldsymbol{R}^ ：n次元実ベクトル空間からm次元実ベクトル空間への写像
$$

$$
例１
\boldsymbol{R}^1 → \boldsymbol{R}^1　　　　一次元ベクトル空間から一次元ベクトル空間
f(x) = 3x     線形変換
線型写像f(x)は式(5-1), (5-2)を満たす。
$$

例２
$$
f:\boldsymbol{R}^3 → \boldsymbol{R}^3が\\
\boldsymbol{x}＝\left[\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
\end{array}\right]，
f(\boldsymbol{x})＝\left[\begin{array}{c}
2x_1ー3x_2ー4x_3\\
x_1ーx_2＋x_3\\
x_1＋2x_2ー7x_3\\
\end{array}\right] \\
と定められる時を考える。\\
この線形変換は、\\
f(\boldsymbol{x}＝A\boldsymbol{x}，  \boldsymbol{x}＝\left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}\right],　　　A＝\left[\begin{array}{ccc}
2 & −３ & −４ \\
1 & −１ &  1  \\
1 & 2  & -7 \\
\end{array}\right]
$$

この時、vectorxが線形変換によって何に変換されるかを求めるプログラム

In [1]:
import numpy as np

A = np.array([
    [2.,-3.,-4.],
    [1.,-1.,1.],
    [1.,2.,-7.],
])
x = np.array([1.,2.,3.]).reshape(-1,1)
np.dot(A,x)#Ax

array([[-16.],
       [  2.],
       [-16.]])

つまりxが表現行列Aである線型写像によってOut1に変換されることが確かめられた。

$$
合成写像\\
2次元ベクトル空間R^2からR^2への線形変換fと、別のR^2からR^2への線形変換gの合成\\
線形変換fの表現行列はA=\left[\begin{array}{cc}
a_{11} & a_{12}\\
a_{21} & a_{22}\\
\end{array}\right]
であり、gの表現行列はB=\left[\begin{array}{cc}
b_{11} & b_{12}\\
b_{21} & b_{22}\\
\end{array}\right]\\
f:R^2 → R^2 \\
\boldsymbol{x} → A\boldsymbol{x}\\
g:R^2 → R^2\\
\boldsymbol{x} → B\boldsymbol{x}\\
fとgの合成写像：g○fと表す\\
x > A\boldsymbol{x} > BA\boldsymbol{x}\\
g○fの表現行列はBA
$$

基本行列の積のイメージ?

$$
f:\boldsymbol{R}^2 → \boldsymbol{R}^3とg:\boldsymbol{R}^3 → \boldsymbol{R}^2の合成\\
線型写像fの表現行列はA=\left[\begin{array}{cc}
1 & -3\\
2 & -2\\
3 & 1 \\
\end{array}\right]
であり、線型写像gの表現行列はB=\left[\begin{array}{ccc}
2 & 1 & 3\\
3 & 1 & 2\\
\end{array}\right]
であるとする。\\
その時の合成写像g○fの表現行列はBA、合成写像f○gの表現行列はABとなりますが、\\それをPythonで計算すると・・・\\
$$

In [1]:
import numpy as np
A = np.array([
    [1., -3],
    [2., -2],
    [3., 1.],
])
B = np.array([
    [2., 1., 3.,],
    [3., 1., 2.],
])

print(np.dot(B,A) ) # BA
print("g○f")
print(np.dot(A,B) ) # AB
print("f○g")

[[13. -5.]
 [11. -9.]]
g○f
[[-7. -2. -3.]
 [-2.  0.  2.]
 [ 9.  4. 11.]]
f○g


画像データからの印象語抽出システムを線型写像で実現
Media-lexicon Transfor-mation Operator


In [17]:
from PIL import Image
import numpy as np
import os

def ext_mean_rgb(filepath):#RGBの平均値を計算
    image = np.array(Image.open(filepath).convert('RGB')).reshape(-1,3)#画像のRGBデータを行列に
    return np.array([np.mean(image[:,0]),np.mean(image[:,1]),np.mean(image[:,2])])#それぞれのRGB値の平均値

from scipy.spatial import distance

def gen_color_vec(rgbvec):#パレットのベクトルからの距離を求める
    colorvec = np.array([])#空の配列
    palette = np.array(
        [
            [255,0,0], #赤
            [255,102,0],  #橙
            [255,255,0],  #黄
            [0,128,0],  #緑
            [0,0,255],  #青
            [128,0,128],  #紫
            [255,0,255],  #ピンク
            [255,255,255],  #白
            [128,128,128],  #グレー
            [0,0,0] #黒
        ]
    )
    for col in palette:#                    colorvecにcolとrgbvecの距離を追加
        colorvec=np.append(colorvec,distance.euclidean(col,rgbvec))#パレットのそれぞれの色とどれくらい近いか
    colorvec=1-colorvec/np.linalg.norm(colorvec,np.inf)# 1  -  ベクトル / ベクトルノルム
        # 近ければ近いほど大きくするため       ノルムで正規化
    return colorvec.reshape(-1,1)

filepath = os.getcwd() + "/pic/img_1.png"

x = gen_color_vec(ext_mean_rgb(filepath))

#表現行列を用意する。本来はカラーイメージスケールなどの研究結果を適用すべきだが、簡単にするため筆者が印象を表す言葉を考えてくれた。
#  　　　　   赤 橙黄緑青 紫ピンクしろ灰黒
A=np.array([[0.5,1,1,1,0,0,1,1,0,-1],           #明るい
            [0,-1,-1,0,0.5,0,-1,-1,0.5,1],      #暗い
            [0,0.5,0.5,0,0,0,1,0,0,0],          #可愛い
            [0,-1,-1,0,1,0,-1,0,1,1],           #悲しい
            [1,1,0.5,-1,-1,0.5,0,0,0,0],        #情熱
            [-1,-1,-1,0.5,1,0,0,0.5,0.5,0.5],   #冷静
            [0,0.5,0.5,1,0,0,0,0,0,0]])         #自然
#                表現行列
np.dot(A,x)

array([[ 1.76619244],
       [-0.97642771],
       [ 0.85662455],
       [-0.66117907],
       [ 1.73992859],
       [-1.29904042],
       [ 0.66185945]])