$$
A\boldsymbol{x}=\boldsymbol{b}
\\
A^{-1}A\boldsymbol{x}=A^{-1}\boldsymbol{b}\\
E\boldsymbol{x}=A^{-1}\boldsymbol{b}\\
\boldsymbol{x}=A^{-1}\boldsymbol{b}
$$

In [2]:
import numpy as np

A=np.array([[2,-3,4],
           [1,-1,1],
           [1,2,-7]])
b=np.array([2,1,-5]).reshape(-1,1)
#Aの逆行列をもとめる
print(np.linalg.inv(A))
np.dot(np.linalg.inv(A),b)


[[-2.5  6.5 -0.5]
 [-4.   9.  -1. ]
 [-1.5  3.5 -0.5]]


array([[4.],
       [6.],
       [3.]])

ガウスの消去法

In [6]:
import numpy as np

def gauss_elimination(A,b):
    Ab=np.concatenate((A, b), axis=1)#[A|b]
    N=Ab.shape[0]#[A|b]の行方向の大きさ
    
    #前進消去
    for i in range(1, N):
        for j in range(i, N):
            Ab[j,:] = Ab[j,i]-Ab[i-1,:]*Ab[j,i-1]/Ab[i-1, i-1]
            
    #後退代入
    for i in range(N-2, -2, -1):
        Ab[i+1,:]=Ab[i+1,:]*(1/Ab[i+1, i+1])
        for j in range(i, -1, -1):
            Ab[j,:] = Ab[j,:]-Ab[i+1]*Ab[j, i+1]/Ab[i+1, i+1]
            
    return Ab[:, N].reshape(-1,1)

A=np.array([[2.,-3.,4.],
           [1.,-1.,1.],
           [1.,2.,-7.]])
b=np.array([2.,1.,-5.]).reshape(-1,1)
gauss_elimination(A,b)

/var/folders/hg/8gzz1y9x1s3bjc9t9w4dmxzr0000gn/T/ipykernel_51500/2835734136.py:14: RuntimeWarning: divide by zero encountered in double_scalars
  Ab[i+1,:]=Ab[i+1,:]*(1/Ab[i+1, i+1])
/var/folders/hg/8gzz1y9x1s3bjc9t9w4dmxzr0000gn/T/ipykernel_51500/2835734136.py:14: RuntimeWarning: invalid value encountered in multiply
  Ab[i+1,:]=Ab[i+1,:]*(1/Ab[i+1, i+1])


array([[       nan],
       [       nan],
       [0.66666667]])